site_name: Roar User Guide
site_url: https://icds-docs.readthedocs.io/en/latest

theme: 
  name: readthedocs
  highlightjs: false
  logo: img/PSU_ICDS_logo_blue.png
  site_favicon: img/favicon.ico
  next_previous: true

extra_css: 
    - css/extra.css

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences

plugins:
    - bootstrap4-blockquotes
    - bootstrap4-tables

nav:
    - Getting Started: 
        - getting-started/system-overview.md
        - getting-started/compute-hardware.md
        - getting-started/before-you-start.md
        - getting-started/connecting-to-rc.md
    - Handling Data:
        - File Storage: handling-data/file-storage.md
        - Managing Files: 
             - handling-data/managing-files/managing-files.md
             - handling-data/managing-files/searching-files.md
             - handling-data/managing-files/archives.md
        - Transfering Data: 
             - handling-data/transfering-data/transfer-overview.md
             - handling-data/transfering-data/globus.md
             - handling-data/transfering-data/portal-transfers.md
             - handling-data/transfering-data/cli-transfers.md
    - Using Software:
        - Using Installed Software: software/modules.md
        - Using Custom Software:
             - Before You Start: software/installing-from-source/considerations.md
             - Installing From Source: software/installing-from-source/installing-from-source.md
             - Using Custom Modules: software/installing-from-source/custom-modules.md
        - Using Containers: software/using-containers.md
        - Package Management:
             - Python Packages: software/loading-packages/python.md
             - R Libraries: software/loading-packages/r.md
             - Using Anaconda: software/loading-packages/anaconda.md
    - Running Jobs:
        - Using the Portal: running-jobs/portal.md
        - Using the Command Line:
             - Scheduler Overview: running-jobs/cli/slurm.md
             - Interactive Jobs: running-jobs/cli/interactive-jobs.md
             - Batch Jobs: running-jobs/cli/batch-jobs.md
        - Paid Resources: 
             - Using Allocations: running-jobs/paid-resources/allocations.md
             - Using Credit Accounts: running-jobs/paid-resources/credit-accounts.md
             - Managing Accounts: running-jobs/paid-resources/managing-accounts.md
    - Roar Restricted:
        - Getting Started: roar-restricted/rr-getting-started.md
        - Handling Data: roar-restricted/rr-handling-data.md
